# Don't deviate too much, just reduce columns and stricter enforcement
edition = "2024"
unstable_features = true
max_width = 80
reorder_impl_items = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_doc_attributes = true
wrap_comments = true
